options:
  path:
      default: ""
      type: string
      description: "Either an organization name or repository in 'org/repo' format"
  token:
      default: ""
      type: string
      description: "Personal Access Token, required for auto registerting with the given url"
  check-interval:
      default: "*/1 * * * *"
      type: string
      description: "Cron interval to check runners, each deployed unit will check on this interval"
  containers:
      default: 3
      type: int
      description: "Quantity of container runners to maintain"
  virtual-machines:
      default: 0
      type: int
      description: "Quantity of virtual machine runners to maintain"